#app name
spring.application.name=salezone

#port
server.port=8089

#database config
spring.datasource.url=jdbc:mysql://localhost:3306/salezonedb
spring.datasource.username=root
spring.datasource.password=9078

#hibernate config
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#file config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#path config
user.profile.image.path=images/users/
product.image.path=images/products/

#frontend url
app.cors.front-end-url=http://localhost:5173

#jwt config
security.jwt.secret=${JWT_SECRET:Q2hhdEdQVF9TdXBlcl9TZWN1cmVfSldUX0tleV9Gb3JfSFMyNTZfSFM1MTJfMjAyNl9Qcm9kdWN0aW9uX1JlYWR5X0tleQ==}
security.jwt.access-ttl-seconds=${JWT_ACCESS_TTL_SECONDS:3600}
security.jwt.refresh-ttl-seconds=${JWT_REFRESH_TTL_SECONDS:86400}
security.jwt.issuer=${JWT_ISSUER:com.ecom.salezone}

#cookie config
security.jwt.refresh-token-cookie-name=refreshToken
security.jwt.cookie-http-only=true
security.jwt.cookie-secure=true
security.jwt.cookie-same-site=lax
security.jwt.cookie-domain=localhost

#frontend url
app.auth.frontend.success-redirect=http://localhost:5173/auth/success
app.auth.frontend.failure-redirect:http://localhost:5173/auth/failure

#oauth2 google config
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email,openid