#app name
spring.application.name=salezone

#port
server.port=8089

#database config
spring.datasource.url=jdbc:mysql://localhost:3306/salezone
spring.datasource.username=root
spring.datasource.password=9078

#hibernate config
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#file config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#path config
user.profile.image.path=images/users/
product.image.path=images/products/