package com.ecom.salezone.dtos;

import com.ecom.salezone.enums.Provider;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@Builder
public class SignupRequestDto {

    /**
     * Unique identifier of the user
     * Generated by backend
     */
    private String userId;

    @NotBlank
    private String userName;

    @Email
    @NotBlank
    private String email;

    @NotBlank
    private String password;

    private String phoneNumber; // optional

    private Provider provider = Provider.LOCAL;
}

