package com.ecom.salezone.dtos;

import com.ecom.salezone.enums.Provider;
import jakarta.validation.constraints.*;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@Builder
public class SignupRequestDto {

    /**
     * Generated by backend
     */
    private String userId;

    // Username: 3-30 characters, only letters, numbers, underscore
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 30, message = "Username must be between 3 and 30 characters")
    @Pattern(
            regexp = "^[a-zA-Z0-9_]+$",
            message = "Username can only contain letters, numbers, and underscores"
    )
    private String userName;

    // Email validation
    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    @Size(max = 100, message = "Email must not exceed 100 characters")
    private String email;

    // Strong password validation
    @NotBlank(message = "Password is required")
    @Size(min = 8, max = 50, message = "Password must be between 8 and 50 characters")
    @Pattern(
            regexp = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).*$",
            message = "Password must contain at least 1 uppercase, 1 lowercase, 1 number, and 1 special character"
    )
    private String password;

    // Optional phone number validation (India example)
//    @Pattern(
//            regexp = "^$|^[0-9]{10,15}$",
//            message = "Phone number must be 10 to 15 digits"
//    )
    private String phoneNumber;

    private Provider provider = Provider.LOCAL;
}