package com.ecom.salezone.dtos;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class UserDto {

    /**
     * Unique identifier of the user
     * Generated by backend
     */
    private String userId;

    /**
     * User display name
     */
    @Size(min = 3, max = 20, message = "Invalid Name !!")
    @Schema(
            name = "username",
            accessMode = Schema.AccessMode.READ_ONLY,
            description = "User name of new user"
    )
    private String userName;

    /**
     * User email (used for login)
     */
    @Pattern(
            regexp = "^[a-z0-9][-a-z0-9._]+@([-a-z0-9]+\\.)+[a-z]{2,5}$",
            message = "Invalid User Email !!"
    )
    @NotBlank(message = "Email is required !!")
    private String email;

    /**
     * Plain password received from client
     * Will be encrypted before saving
     */
    @NotBlank(message = "Password is required !!")
    @Size(min = 8, max = 12, message = "Password length should between 8 to 12 !!")
    private String password;

    /**
     * Gender of user
     */
    @Size(min = 4, max = 6, message = "Invalid gender !!")
    private String gender;

    /**
     * Short description about user
     */
    @NotBlank(message = "Write something about yourself !!")
    private String about;

    /**
     * Phone number of user
     */
    @Size(min = 10, max = 10, message = "Invalid Number !!")
    @NotBlank(message = "Phone number is required !!")
    private String phoneNumber;

    /**
     * Profile image name
     * Custom validation can be added
     */
    // @ImageNameValid (custom validator - optional)
    private String imageName;

    /**
     * Roles assigned to user
     */
    private Set<RoleDto> roles = new HashSet<>();
}

